# Cấu hình luật gán nhãn
backend:
  - changed-files:
      - any-glob-to-any-file: "be/**/*"

web:
  - changed-files:
      - any-glob-to-any-file: "web-fe/**/*"

mobile:
  - changed-files:
      - any-glob-to-any-file: "mobile-fe/**/*"

ai:
  - changed-files:
      - any-glob-to-any-file: "ai/**/*"

documentation:
  - changed-files:
      - any-glob-to-any-file: "**/README.md"

ci-cd:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**/*"
