name: Emerald Skyline CI
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  code-quality:
    name: Check Code Quality (Biome)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Bắt buộc phải có để Biome tính toán được file nào vừa bị change

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome check (CI mode)
        # Thêm --since=main để tường minh
        run: biome ci --changed --since=main --no-errors-on-unmatched .

  build-backend:
    name: Build NestJS Backend
    needs: code-quality # check format và lint trước khi build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (Version 22)
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: be/package-lock.json

      - name: Install Backend Deps
        run: cd be && npm ci

      - name: Build Backend
        run: cd be && npm run build

  build-frontend:
    name: Build React Web
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (Version 22)
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: web-fe/package-lock.json

      - name: Install Frontend Deps
        run: cd web-fe && npm ci

      - name: Build Frontend
        run: cd web-fe && npm run build

  # Job Test (Khi nào viết test case thì mở ra dùng)
  # test:
  #   name: Run Tests
  #   needs: code-quality
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'npm'
  #     - name: Test backend
  #       run: cd be && npm ci && npm run test
